version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - ls -R
  build:
    commands:
      - echo "Build phase - preparing static site package"
      - mkdir -p build
      - cp -r * build/
      - echo "Static site copied to build/ folder"
  post_build:
    commands:
      - echo "Packaging artifacts for CodeDeploy..."
      - cd build
      - zip -r ../static-website.zip . -x "*.git*" "buildspec.yml"
      - cd ..
      - echo "Build completed. Artifacts ready for CodeDeploy."

artifacts:
  files:
    - static-website.zip
    - appspec.yml
  discard-paths: yes
