version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - ls -R

  build:
    commands:
      - echo "Build phase - no build needed for static website"

  post_build:
    commands:
      - echo "Deploying static site to S3..."
      - aws s3 sync . s3://photograph-gallery --delete --exclude "*.git*" --exclude "buildspec.yml" --exclude "appspec.yml"

artifacts:
  files:
    - '**/*'
