version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - ls -R

  build:
    commands:
      - echo "Build phase - deploying static website to S3..."
      - aws s3 sync . s3://photograph-gallery --delete --exclude ".git/*" --exclude "buildspec.yml" --exact-timestamps

artifacts:
  files:
    - '**/*'
  base-directory: build
  discard-paths: yes
  name: input-build-arti

cache:
  paths:
    - '/root/.cache/pip/**/*'

