version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli

  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - ls -R

  build:
    commands:
      - echo "No direct deploy here; just prep files if needed"


artifacts:
  files:
    - '**/*'

