version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "Installing dependencies..."
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo "Pre-build phase started..."
      - ls -R
  build:
    commands:
      - echo "Build phase - zipping static website files"
      - zip -r static-website.zip . -x "*.git*" "buildspec.yml"
  post_build:
    commands:
      - echo "Build completed. Artifacts ready for CodeDeploy."

artifacts:
  files:
    - static-website.zip
    - appspec.yml
  discard-paths: yes
